# Generated by Django 4.2.3 on 2023-08-14 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_advertisements14', '0005_advertisements14_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements14',
            name='auction',
            field=models.BooleanField(help_text='Отметьте, если возможен торг', verbose_name='торг'),
        ),
        migrations.AlterField(
            model_name='advertisements14',
            name='connection',
            field=models.BooleanField(default=True, help_text='Отметьте, возможна ли связь с продавцом', verbose_name='связь'),
        ),
        migrations.AlterField(
            model_name='advertisements14',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='advertisements14',
            name='image',
            field=models.ImageField(upload_to='advertisements/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='advertisements14',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='advertisements14',
            name='title',
            field=models.CharField(max_length=128, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='advertisements14',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
