# Generated by Django 4.2.3 on 2023-08-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements14', '0007_alter_advertisements14_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements14',
            name='image',
            field=models.ImageField(default='adv.png', upload_to='advertisements/', verbose_name='изображение'),
        ),
    ]
